### ISSUE TITLE
All bus are locked (QBCore)

### ISSUE THREAD

**Issue by Belorico** [FedericoDeBona/publictransport_2#1]
Can`t get in on any BUS. All are closed.

**Comment by FedericoDeBona** [comment]
It may be a lock script. Some people had the same issue with the test version so you might add the bus hash to a config file. The link to the test script is in the first line of the post in the forum.

**Comment by Belorico** [comment]
Sorry Federico... Didn`t understand if you have a fix...

QBCore has qb-vehiclekeys that sets all vehicles closed. It doesn`t have any whitelist for vehicles.

**Comment by FedericoDeBona** [comment]
Try to ask on the forum under my post maybe someone knows how to solve this

**Comment by Belorico** [comment]
I have solved it.. thank you
